### ISSUE TITLE
Talk Proposal: Laravel Vapor is awesome

### ISSUE THREAD

**Issue by gregskerman** [Brisbane-Laravel-Meetup/meetups#12]
When Laravel Vapor came to market, we were pretty quick to adopt it. In this talk I would like to discuss

- How we transitioned a bunch of legacy systems to run on Lambda using Vapor
- Some of the pitfalls and problems we ran into along the way, and how we overcame them
- A look at the cost savings we were able to realise along the way
- The benefits of a fully autoscaled platform

**Comment by jryd** [comment]
After a long hiatus, we're restarting the Brisbane Laravel Meetup.

If you're still interested in presenting this talk [at our next meetup](https://www.meetup.com/bne-laravel-meetup/events/296922338/) then please let us know!

In the meantime, we'll close this proposal so that we can start from a clean slate.
