### ISSUE TITLE
Talk Proposal: Email chatroom (listserv) in Laravel

### ISSUE THREAD

**Issue by hayleybech** [Brisbane-Laravel-Meetup/meetups#18]
Abstract
- What is an email chatroom?
- Why did I decide to make one?
- Overview of the email system's architecture
- Deep dive into the code
- Weaknesses and Opportunities

**Comment by jryd** [comment]
After a long hiatus, we're restarting the Brisbane Laravel Meetup.

If you're still interested in presenting this talk [at our next meetup](https://www.meetup.com/bne-laravel-meetup/events/296922338/) then please let us know!

In the meantime, we'll close this proposal so that we can start from a clean slate.
